export const DATAREF_STR = {
  VS: 'sim/flightmodel/position/local_vy',
  GEAR_FORCE: 'sim/flightmodel/forces/fnrml_gear',
  G_FORCE: 'sim/flightmodel2/misc/gforce_normal',
  AGL: 'sim/flightmodel/position/y_agl',
  ELEVATION: 'sim/flightmodel/position/elevation',
  GS: 'sim/flightmodel/position/groundspeed',
  N1: 'sim/cockpit2/engine/indicators/N1_percent[0]',
  PITCH: 'sim/flightmodel/position/theta',
  IAS: 'sim/cockpit2/gauges/indicators/airspeed_kts_pilot',
  LAT: 'sim/flightmodel/position/latitude',
  LNG: 'sim/flightmodel/position/longitude',
  TS: 'sim/network/misc/network_time_sec',
  TAIL_NUMBER_1: 'sim/aircraft/view/acf_tailnum[0]',
  TAIL_NUMBER_2: 'sim/aircraft/view/acf_tailnum[1]',
  TAIL_NUMBER_3: 'sim/aircraft/view/acf_tailnum[2]',
  TAIL_NUMBER_4: 'sim/aircraft/view/acf_tailnum[3]',
  TAIL_NUMBER_5: 'sim/aircraft/view/acf_tailnum[4]',
  TAIL_NUMBER_6: 'sim/aircraft/view/acf_tailnum[5]',
  TAIL_NUMBER_7: 'sim/aircraft/view/acf_tailnum[6]',
  TAIL_NUMBER_8: 'sim/aircraft/view/acf_tailnum[7]',
  ICAO_1: 'sim/aircraft/view/acf_ICAO[0]',
  ICAO_2: 'sim/aircraft/view/acf_ICAO[1]',
  ICAO_3: 'sim/aircraft/view/acf_ICAO[2]',
  ICAO_4: 'sim/aircraft/view/acf_ICAO[3]',
  ICAO_5: 'sim/aircraft/view/acf_ICAO[4]',
  ICAO_6: 'sim/aircraft/view/acf_ICAO[5]',
  ICAO_7: 'sim/aircraft/view/acf_ICAO[6]',
  ICAO_8: 'sim/aircraft/view/acf_ICAO[7]',
  ICAO_9: 'sim/aircraft/view/acf_ICAO[8]',
  ICAO_10: 'sim/aircraft/view/acf_ICAO[9]',
  ICAO_11: 'sim/aircraft/view/acf_ICAO[10]',
  ICAO_12: 'sim/aircraft/view/acf_ICAO[11]',
  ICAO_13: 'sim/aircraft/view/acf_ICAO[12]',
  ICAO_14: 'sim/aircraft/view/acf_ICAO[13]',
  FUEL_WEIGHT: 'sim/flightmodel/weight/m_fuel_total',
  TOTAL_WEIGHT: 'sim/flightmodel/weight/m_total',
  EMPTY_WEIGHT: 'sim/aircraft/weight/acf_m_empty',
  HEADING: 'sim/flightmodel/position/mag_psi',
  PAUSED: 'sim/time/paused',
  ZULU_TIME: 'sim/time/zulu_time_sec',
};
export const DATAREF_FEQ = 5; // per second
export const DATAREF_FEQ_LANDING = 30; // per second
export const DATAREF_BATCH_SIZE = 50;
export const XAA_ID = '9ead9f02-ddd1-4166-91ee-95a4ba9987d1';
